### ISSUE TITLE
Photo doesn't register

### ISSUE THREAD

**Issue by AqwelF** [SimpleMobileTools/Simple-Camera#169] opened 2018-06-14 08:03 UTC
Since recent update, when i take a picture, the photo freeze and stay on screen but nothing happen. When i clic back button a toast said "picture is not registered"

Edit : i remove and reinstall it same probleme. I go back to 4.0.0 and works fine

Phone : honor 9
Os : oreo 8.0 EMUI 8.1 (stock rom)
App vers : 4.1.1

**Comment by AqwelF** [comment] 2018-06-16 06:29
Hi i switched yesterday to a custom rom and now it works great.

**Comment by tibbi** [comment] 2018-06-16 07:33
well there is a million things related to handling the Camera done differently depending on the manufacturer, rom and Android OS version, thats why theres many glitches that I just cannot reproduce. Ill still take a look at this someday.

**Comment by Kingwad** [comment] 2018-06-20 22:59
Moto Z, Oreo 8.0.0

Had this bug in 4.1.1. Fixed in 4.1.2, except now images are rotated 90 degrees.

**Comment by tibbi** [comment] 2018-07-09 22:05
should be fixed in 4.1.3, photo rotation too

**Closed by tibbi** 2018-07-09 22:05 UTC
Labels: bug
