### ISSUE TITLE
[feature request] Qr reader/history

### ISSUE THREAD

**Issue by weisshs** [SimpleMobileTools/Simple-Camera#411] opened 2023-05-12 18:39 UTC
Hello! I have been using and enjoying simple camera for a while, as it is the only camera app that runs well on my slow phone. 

One thing I think would improve the app drastically is a basic qr reader and history of codes that have been read. I understand that the simple mobile tools are meant to be as simple as possible, but this seems like such a practical addition that could be added without ruining the "simple" aspect of this app.

 Rather than having to unlock the phone, open a separate app to scan a code and immediately see  it in the browser, It would be much simpler and quicker to just open the camera, have the app save the qr and link in a basic "history" list, and view the link whenever convenient. 

Thank you!

**Comment by tibbi** [comment] 2023-05-12 19:42
duplicate of #73

**Closed by tibbi** 2023-05-12 19:42 UTC
